name: Windows Custom (Portable, Secrets)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust (MSVC)
        uses: dtolnay/rust-toolchain@stable

      - name: Build (release)
        shell: powershell
        run: cargo build --release

      - name: Create RustDesk2.toml with secrets
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          $server = "${{ secrets.RD_SERVER }}"
          $key    = "${{ secrets.RD_KEY }}"
          if (-not $server) { throw "RD_SERVER secret missing" }
          if (-not $key)    { throw "RD_KEY secret missing" }
          if ($key -notmatch "^hbbs_pubkey_1=") { throw "RD_KEY must start with hbbs_pubkey_1=" }
          @"
[server]
host = "$server"
key  = "$key"
"@ | Out-File -FilePath dist\RustDesk2.toml -Encoding UTF8

      - name: Collect binaries
        shell: powershell
        run: |
          Copy-Item target\release\rustdesk.exe dist\RustDesk.exe

      - name: Package zip
        shell: powershell
        run: |
          Compress-Archive -Path dist\* -DestinationPath rustdesk-windows-custom-portable.zip -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-custom-portable
          path: rustdesk-windows-custom-portable.zip
          if-no-files-found: error
